name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: YOUR_CLIENT_ID
        tenant-id: YOUR_TENANT_ID
        subscription-id: YOUR_SUBSCRIPTION_ID
        auth-type: IDENTITY

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve
