name: Deploy to Azure

on:
  push:
    branches:
      - master


permissions:
  id-token: write
  contents: read      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscription: true


    - name: Install Terraform CLI
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6  # Always use the latest version
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan 

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve

    - name: Terraform Destroy
      run: terraform destroy
