name: 'Terraform Deploy to Azure'

on:
  push:
    branches:
      - master

# permissions:
#   contents: read
     # This is enough for repo checkout # To read the repo content

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.0  # Use your required version

    - name: Azure Login via Service Principal
      uses: azure/login@v2
      with:
        auth-type: SERVICE_PRINCIPAL          # 🔴 This is mandatory     
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # client-id: ${{ secrets.CLIENT_ID }}
        # tenant-id: ${{ secrets.TENANT_ID }}
        # subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        # client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan #-var="client_id=${{ secrets.CLIENT_ID }}" -var="client_secret=${{ secrets.CLIENT_SECRET }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve #-var="client_id=${{ secrets.CLIENT_ID }}" -var="client_secret=${{ secrets.CLIENT_SECRET }}
