name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: IDENTITY

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve
